name: d23_dyuksha
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  motion_toast: ^2.6.5
  flutter_native_splash:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  share_plus: ^6.3.1
  async: 2.10.0
  confetti: ^0.7.0
  animated_splash_screen:
  cloud_firestore: ^4.4.4
  cached_network_image: ^3.2.3
  transformer_page_view: ^0.1.6
  firebase_storage: ^11.0.16
  firebase_performance: ^0.9.0+16
  pdf: ^3.9.0
  printing: ^5.10.1
  internet_connection_checker: ^1.0.0+1
  file_picker: ^5.2.6
  animated_text:
    git:
      url: https://github.com/josorio9111/animated_text.git
  glitcheffect: ^1.1.1
  f_glitch: ^0.1.2
flutter_native_splash:
  ios: false
  web: false
  image: assets/Black.png
  color: "#000000"
  android_12:
    image: assets/Black.png
    color: "#000000"
flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/Dlogo2.png"
  ios: false
  image_path: "assets/Dlogo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    # image_path: "path/to/image.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: false
    #image_path: "path/to/image.png"
    #icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    #image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
