name: d23_dyuksha
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  motion_toast: ^2.6.5
  flutter_native_splash:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  share_plus: ^6.3.1
  async: 2.10.0
  confetti: ^0.7.0
  google_sign_in: ^6.0.2
  animated_splash_screen:
  cloud_firestore: ^4.4.4
  cached_network_image: ^3.2.3
  transformer_page_view: ^0.1.6
  firebase_storage: ^11.0.16
  firebase_performance: ^0.9.0+16
  internet_connection_checker: ^1.0.0+1
flutter_native_splash:
  ios: false
  web: false
  image: assets/Black.png
  color: "#000000"
  android_12:
    image: assets/Black.png
    color: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
